# Common vars
availability_zone: melbourne-qh2-uom
instance_image: bbaf16f8-2484-48d7-b455-42209cc4b8d2
instance_key_name: mrc

instance_flavor: uom.mse.2c9g

# Volume
volumes:
  - vol_name: vol-couchdb
    vol_size: 100

# Security group
security_groups:
  - name: ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: coughdb-test
    description: "security group for HTTP"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0


# Instance
instances:
  - name: coughdb
    volumes: ["vol-couchdb"]

