# Common vars
availability_zone: melbourne-qh2-uom
instance_image: bbaf16f8-2484-48d7-b455-42209cc4b8d2
instance_key_name: mrc

instance_flavor: uom.mse.1c4g

# Volume
volumes:
  - vol_name: vol-demo
    vol_size: 100

# Security group
security_groups:
  - name: ssh
    description: "security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http
    description: "security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb
    description: "security group for couchdb"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: backend
    description: "security group for cluster"
    protocol: tcp
    port_range_min: 3000
    port_range_max: 3000
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: demo
    volumes: ["vol-demo"]

